### ISSUE TITLE
文件上传可以在文件夹里看见上传的文件，但是还是报错上传失败，第二次在传就报错文件合并失败

### ISSUE THREAD

**Issue by ding5892** [YPTopMan/FileUpload#1]

**Comment by YPTopMan** [comment]
> _没有提供说明。_

解决了吗？

**Comment by ding5892** [comment]
没有，



------------------ 原始邮件 ------------------
发件人: "YPTopMan"<notifications@github.com>; 
发送时间: 2019年6月4日(星期二) 下午3:25
收件人: "YPTopMan/FileUpload"<FileUpload@noreply.github.com>; 
抄送: "進"<1534368026@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YPTopMan/FileUpload] 文件上传可以在文件夹里看见上传的文件，但是还是报错上传失败，第二次在传就报错文件合并失败 (#1)



 
没有提供说明。
  
解决了吗？

**Comment by YPTopMan** [comment]
> 没有，
提交了修复

**Comment by YPTopMan** [comment]
有什么问题可以继续反馈

**Comment by ding5892** [comment]
好的，谢谢
 



------------------ 原始邮件 ------------------
发件人: "YPTopMan"<notifications@github.com>; 
发送时间: 2019年6月4日(星期二) 下午3:48
收件人: "YPTopMan/FileUpload"<FileUpload@noreply.github.com>; 
抄送: "進"<1534368026@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YPTopMan/FileUpload] 文件上传可以在文件夹里看见上传的文件，但是还是报错上传失败，第二次在传就报错文件合并失败 (#1)




有什么问题可以继续反馈
