### ISSUE TITLE
上传大于20M的文件即异常

### ISSUE THREAD

**Issue by JaneConan** [YPTopMan/FileUpload#2]

**Comment by YPTopMan** [comment]
20M 就报错？ 有错误截图吗？

**Comment by YPTopMan** [comment]
40m 的可以上传

**Comment by JaneConan** [comment]
如何不限制，或咱们指定大小限制呢？您方便的话，麻烦Demo一下

**Comment by YPTopMan** [comment]
> 如何不限制，或咱们指定大小限制呢？您方便的话，麻烦Demo一下

分为前端和后端限制大小，前端是设置组件的小大，后端是设置服务器上的最大接收数量。
你前端用的是百度的上传插件的话，
![image](https://user-images.githubusercontent.com/11879898/60144784-54aec680-97f6-11e9-985d-d625820f8183.png)
